#ifndef UISTYLES_H
#define UISTYLES_H

#include <QString>

namespace UiStyles {

inline QString appStyleSheet()
{
    return QStringLiteral(
        "* { font-size: 11pt; }"
        "QMainWindow { background-color: #F3F5F7; }"
        "QMenuBar { background-color: #FFFFFF; border-bottom: 1px solid #D9DEE7; padding: 4px; font-size: 11pt; }"
        "QMenuBar::item { color: #222222; background: transparent; padding: 6px 12px; }"
        "QMenuBar::item:selected { background-color: #E8F1FD; color: #222222; border-radius: 4px; }"
        "QMenu { background-color: #FFFFFF; border: 1px solid #D9DEE7; font-size: 11pt; padding: 4px 0; }"
        "QMenu::item { color: #222222; background-color: transparent; padding: 8px 28px; }"
        "QMenu::item:selected { background-color: #E8F1FD; color: #222222; }"
        "QMenu::item:hover { background-color: #EEF4FC; color: #222222; }"
        "QMenu::separator { height: 1px; background: #D9DEE7; margin: 4px 8px; }"
        "QToolBar { background-color: #FFFFFF; border: none; spacing: 8px; padding: 6px 10px; }"
        "QToolBar QToolButton {"
        "  background-color: #FFFFFF; color: #222222;"
        "  border: 1px solid #D9DEE7; border-radius: 5px;"
        "  padding: 6px 14px; min-height: 32px; font-size: 11pt;"
        "}"
        "QToolBar QToolButton:hover { background-color: #EEF4FC; border-color: #2F80ED; color: #222222; }"
        "QToolBar QToolButton:pressed { background-color: #DCE9FA; color: #222222; }"
        "QTabWidget::pane { border: 1px solid #D9DEE7; border-radius: 6px; background: #FFFFFF; }"
        "QTabBar::tab {"
        "  background: #EEF1F5; border: 1px solid #D9DEE7;"
        "  padding: 10px 18px; margin-right: 3px;"
        "  border-top-left-radius: 6px; border-top-right-radius: 6px;"
        "  font-size: 11pt; min-height: 28px;"
        "}"
        "QTabBar::tab:selected { background: #FFFFFF; font-weight: bold; color: #2F80ED; }"
        "QTabBar::tab:hover { background: #F0F4FA; color: #222222; }"
        "QTabBar::tab:selected:hover { background: #FFFFFF; color: #2F80ED; }"
        "QGroupBox {"
        "  font-weight: bold; font-size: 12pt; color: #222222;"
        "  border: 1px solid #D9DEE7; border-radius: 6px;"
        "  margin-top: 14px; padding: 18px 12px 12px 12px; background: #FFFFFF;"
        "}"
        "QGroupBox::title { subcontrol-origin: margin; left: 12px; padding: 0 6px; }"
        "QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox {"
        "  background: #FFFFFF; color: #222222;"
        "  border: 1px solid #D9DEE7; border-radius: 4px;"
        "  padding: 4px 8px; min-height: 28px; font-size: 11pt;"
        "}"
        "QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus { border-color: #2F80ED; }"
        "QLabel { color: #222222; font-size: 11pt; }"
        "QPushButton {"
        "  background-color: #2F80ED; color: #FFFFFF; border: none;"
        "  border-radius: 5px; padding: 8px 16px; min-height: 32px;"
        "  font-weight: bold; font-size: 11pt;"
        "}"
        "QPushButton:hover { background-color: #2569C7; }"
        "QPushButton:pressed { background-color: #1F5AA8; }"
        "QPushButton:disabled { background-color: #B8C5D6; color: #F0F0F0; }"
        "QPushButton#secondaryBtn {"
        "  background-color: #FFFFFF; color: #222222;"
        "  border: 1px solid #D9DEE7; font-weight: normal;"
        "}"
        "QPushButton#secondaryBtn:hover { background-color: #F3F5F7; color: #222222; }"
        "QListWidget { background: #FFFFFF; border: 1px solid #D9DEE7; border-radius: 6px; font-size: 11pt; }"
        "QListWidget::item { padding: 8px 10px; min-height: 32px; color: #222222; }"
        "QListWidget::item:hover { background-color: #F0F4FA; color: #222222; }"
        "QListWidget::item:selected { background-color: #E8F1FD; color: #1E3A5F; }"
        "QListWidget::item:selected:hover { background-color: #D6E8FC; color: #1E3A5F; }"
        "QStatusBar { background-color: #FFFFFF; border-top: 1px solid #D9DEE7; color: #444444; font-size: 11pt; }"
        "QStatusBar QLabel { padding: 4px 10px; font-size: 11pt; }"
        "QSplitter::handle { background-color: #D9DEE7; width: 4px; }"
        "QSplitter::handle:hover { background-color: #2F80ED; }"
        "QLabel#panelTitle { font-size: 12pt; font-weight: bold; color: #222222; padding: 4px 0; }"
        "QLabel#emptyHint { color: #666666; font-size: 13pt; font-weight: bold; padding: 24px 12px 6px 12px; }"
        "QLabel#emptySubHint { color: #888888; font-size: 11pt; padding: 0 12px 24px 12px; }"
        "QLabel#multiHint { color: #2F80ED; font-size: 13pt; font-weight: bold; padding: 24px 12px; }"
        "QLabel#objectTitle { font-size: 12pt; font-weight: bold; color: #222222; }"
        "QLabel#codeLabel { color: #666666; font-size: 11pt; }"
        "QFrame#canvasFrame { background-color: #E8EAED; border: 1px solid #D9DEE7; border-radius: 4px; }"
        "QFrame#toolPalette {"
        "  background-color: #F8FAFC; border-right: 1px solid #E5E7EB;"
        "  min-width: 88px; max-width: 88px;"
        "}"
        "QFrame#toolPalette QLabel#toolPaletteTitle {"
        "  font-size: 11pt; font-weight: bold; color: #666666; padding: 0 0 6px 0;"
        "}"
        "QFrame#toolPalette QToolButton#toolPaletteButton {"
        "  background-color: transparent; border: 1px solid transparent; border-radius: 8px;"
        "  padding: 0px; margin: 0px;"
        "  min-width: 56px; max-width: 56px; min-height: 56px; max-height: 56px;"
        "}"
        "QFrame#toolPalette QToolButton#toolPaletteButton:hover {"
        "  background-color: #E8F1FF; border-color: transparent;"
        "}"
        "QFrame#toolPalette QToolButton#toolPaletteButton:checked {"
        "  background-color: #2F80ED; border-color: transparent;"
        "}"
        "QFrame#toolPalette QToolButton#toolPaletteButton:checked:hover {"
        "  background-color: #2569C7; border-color: transparent;"
        "}"
        "QWidget#rightPanelHost { background-color: #F3F5F7; }"
        "QCheckBox { font-size: 11pt; spacing: 6px; }"
        "QFormLayout QLabel { min-width: 72px; }"
    );
}

} // namespace UiStyles

#endif // UISTYLES_H
